2023-01-03 23:53:20,101 (40018ab808) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: 819d367 (Fri Sep 23 01:15:17 UTC 2022)
2023-01-03 23:53:20,109 (40018ab808) :  DEBUG (core:361) - Using the elevated policy
2023-01-03 23:53:20,115 (40018ab808) :  DEBUG (core:450) - Starting runtime component.
2023-01-03 23:53:20,164 (40018ab808) :  DEBUG (core:450) - Starting caching component.
2023-01-03 23:53:20,177 (40018ab808) :  DEBUG (core:450) - Starting data component.
2023-01-03 23:53:20,181 (40018ab808) :  DEBUG (core:450) - Starting networking component.
2023-01-03 23:53:20,188 (40018ab808) :  DEBUG (networking:265) - No cookie jar found
2023-01-03 23:53:20,226 (40018ab808) :  DEBUG (networking:428) - Setting the default network timeout to 20.0
2023-01-03 23:53:20,237 (40018ab808) :  DEBUG (core:450) - Starting localization component.
2023-01-03 23:53:20,242 (40018ab808) :  INFO (localization:409) - Setting the default locale to en-us
2023-01-03 23:53:20,246 (40018ab808) :  DEBUG (core:450) - Starting messaging component.
2023-01-03 23:53:20,255 (40018ab808) :  DEBUG (core:450) - Starting debugging component.
2023-01-03 23:53:20,258 (40018ab808) :  DEBUG (core:450) - Starting services component.
2023-01-03 23:53:20,262 (40018ab808) :  DEBUG (core:450) - Starting myplex component.
2023-01-03 23:53:20,266 (400da68b38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/system/messaging/clear_events/com.plexapp.agents.thetvdb'
2023-01-03 23:53:20,268 (40018ab808) :  DEBUG (core:450) - Starting notifications component.
2023-01-03 23:53:20,987 (40018ab808) :  DEBUG (accessor:68) - Creating a new model access point for provider com.plexapp.agents.thetvdb in namespace 'metadata'
2023-01-03 23:53:21,033 (40018ab808) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2023-01-03 23:53:21,069 (40018ab808) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes'
2023-01-03 23:53:21,080 (40018ab808) :  CRITICAL (runtime:1299) - Exception getting hosted resource hashes (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-819d3678c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 1293, in get_resource_hashes
    json = self._core.networking.http_request("http://127.0.0.1:32400/:/plugins/com.plexapp.system/resourceHashes", timeout=10).content
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-819d3678c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 242, in content
    return self.__str__()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-819d3678c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 220, in __str__
    self.load()
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-819d3678c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/networking.py", line 158, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/plexmediaserver/Resources/Python/python27.zip/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found

2023-01-03 23:53:21,124 (400e6fdb38) :  DEBUG (services:265) - Plug-in is not daemonized - loading services from system
2023-01-03 23:53:21,125 (40018ab808) :  DEBUG (runtime:1117) - Created a thread named 'load_all_services'
2023-01-03 23:53:21,136 (40018ab808) :  DEBUG (runtime:1117) - Created a thread named 'get_server_info'
2023-01-03 23:53:21,140 (400e6fdb38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0J1bmRsZVNlcnZpY2U6QWxsU2VydmljZXM_/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMApyMAo_'
2023-01-03 23:53:21,152 (400e74eb38) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400'
2023-01-03 23:53:21,164 (40018ab808) :  DEBUG (core:150) - Finished starting framework core
2023-01-03 23:53:21,167 (40018ab808) :  DEBUG (core:560) - Loading plug-in code
2023-01-03 23:53:21,309 (400e6fdb38) :  DEBUG (services:362) - Loaded services
2023-01-03 23:53:21,347 (400e74eb38) :  DEBUG (core:538) - Machine identifier is 83722fb6ea7f2b2c2a4872a99006ce76878d8cc8
2023-01-03 23:53:21,362 (400e74eb38) :  DEBUG (core:539) - Server version is 1.29.0.6244-819d3678c
2023-01-03 23:53:21,375 (400e727b38) :  DEBUG (services:438) - No shared code to load
2023-01-03 23:53:23,317 (40018ab808) :  DEBUG (core:566) - Finished loading plug-in code
2023-01-03 23:53:23,324 (40018ab808) :  DEBUG (agentkit:1132) - Creating new agent class called TVDBAgent
2023-01-03 23:53:23,337 (40018ab808) :  DEBUG (agentkit:937) - Updating agent information: [{'media_types': ['TV_Show'], 'accepts_from': None, 'fallback_agent': None, 'contributes_to': None, 'languages': ['en', 'fr', 'zh', 'sv', 'no', 'da', 'fi', 'nl', 'de', 'it', 'es', 'pl', 'hu', 'el', 'tr', 'ru', 'he', 'ja', 'pt', 'cs', 'ko', 'sl', 'hr'], 'persist_stored_files': True, 'version': 0, 'primary_provider': True, 'prefs': True, 'name': 'TheTVDB'}]
2023-01-03 23:53:23,358 (40018ab808) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/:/plugins/com.plexapp.system/messaging/function/X0FnZW50U2VydmljZTpVcGRhdGVJbmZv/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQo1CmRpY3QKbGlzdApkaWN0Cmxpc3QKbGlzdAoyCnMyNgpjb20ucGxleGFwcC5hZ2VudHMudGhldHZkYnMxMAppZGVudGlmaWVycjEKczEwCmFnZW50X2luZm8xCnIyCjEwCnIzCnMxMQptZWRpYV90eXBlc25zMTIKYWNjZXB0c19mcm9tbnMxNApmYWxsYmFja19hZ2VudG5zMTQKY29udHJpYnV0ZXNfdG9yNApzOQpsYW5ndWFnZXNiMXMyMApwZXJzaXN0X3N0b3JlZF9maWxlc2kwCnM3CnZlcnNpb25iMXMxNgpwcmltYXJ5X3Byb3ZpZGVyYjFzNQpwcmVmc3M3ClRoZVRWREJzNApuYW1lMQpzNwpUVl9TaG93MjMKczIKZW5zMgpmcnMyCnpoczIKc3ZzMgpub3MyCmRhczIKZmlzMgpubHMyCmRlczIKaXRzMgplc3MyCnBsczIKaHVzMgplbHMyCnRyczIKcnVzMgpoZXMyCmphczIKcHRzMgpjc3MyCmtvczIKc2xzMgpocnIwCg__'
2023-01-03 23:53:37,007 (40018ab808) :  INFO (core:611) - Started plug-in
2023-01-03 23:53:37,013 (40018ab808) :  DEBUG (socketinterface:160) - Starting socket server
2023-01-03 23:53:37,041 (40018ab808) :  DEBUG (runtime:1117) - Created a thread named 'start'
2023-01-03 23:53:37,048 (40018ab808) :  INFO (socketinterface:184) - Socket server started on port 38531
2023-01-03 23:53:37,053 (40018ab808) :  INFO (pipeinterface:25) - Entering run loop
2023-01-03 23:53:37,057 (40018ab808) :  DEBUG (runtime:717) - Handling request GET /:/prefixes
2023-01-03 23:53:37,070 (40018ab808) :  DEBUG (runtime:814) - Found route matching /:/prefixes
2023-01-03 23:53:37,081 (40018ab808) :  DEBUG (runtime:924) - Response: [200] MediaContainer, 151 bytes
2023-01-03 23:53:37,115 (40117f0b38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.thetvdb
2023-01-03 23:53:37,137 (4011813b38) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.thetvdb
2023-01-03 23:53:37,250 (40117f0b38) :  CRITICAL (runtime:493) - Exception matching route for path "/" (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-819d3678c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 464, in match_route
    raise Framework.exceptions.FrameworkException("No route found matching '%s'" % path)
FrameworkException: No route found matching '/'

2023-01-03 23:53:37,257 (4011813b38) :  CRITICAL (runtime:493) - Exception matching route for path "/" (most recent call last):
  File "/usr/lib/plexmediaserver/Resources/Plug-ins-819d3678c/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components/runtime.py", line 464, in match_route
    raise Framework.exceptions.FrameworkException("No route found matching '%s'" % path)
FrameworkException: No route found matching '/'

2023-01-03 23:53:37,264 (4011813b38) :  ERROR (runtime:846) - Could not find route matching /:/plugins/com.plexapp.agents.thetvdb
2023-01-03 23:53:37,258 (40117f0b38) :  ERROR (runtime:846) - Could not find route matching /:/plugins/com.plexapp.agents.thetvdb
2023-01-03 23:53:37,281 (40117f0b38) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
2023-01-03 23:53:37,274 (4011813b38) :  DEBUG (runtime:88) - Sending packed state data (107 bytes)
2023-01-03 23:53:37,298 (4011813b38) :  DEBUG (runtime:924) - Response: [404] NoneType, 0 bytes
2023-01-03 23:53:37,287 (40117f0b38) :  DEBUG (runtime:924) - Response: [404] NoneType, 0 bytes
